## Initial Event Preparation
- Occurs pre-event
- Instantiate class and define bracket format via the dictionary and lists of tuples as shown below

In [1]:
from SART_Class_v3 import SART
import pandas as pd

In [2]:
#ALL UPDATES FOR 2018 COMPLETE, INCLUDES CHANGE TO 64 PERSON BRACKET
#Round 0 seeding assignments for Round 1 Heats:
r0_seeds = {'Heat 101': [1, 32, 33, 64], 'Heat 102': [16, 17, 48, 49],
    'Heat 103': [8, 25, 40, 57], 'Heat 104': [9, 24, 41, 56],
    'Heat 105': [4, 29, 36, 61], 'Heat 106': [13, 20, 45, 52],
    'Heat 107': [5, 28, 37, 60], 'Heat 108': [12, 21, 44, 53],
    'Heat 109': [2, 31, 34, 63], 'Heat 110': [15, 18, 47, 50],
    'Heat 111': [7, 26, 39, 58], 'Heat 112': [10, 23, 42, 55],
    'Heat 113': [3, 30, 35, 62], 'Heat 114': [14, 19, 46, 51],
    'Heat 115': [6, 27, 38, 59], 'Heat 116': [11, 22, 43, 54]}

r0_seeds_fiftysix = {'Heat 101': [1, 32, 33], 'Heat 102': [16, 17, 48, 49],
    'Heat 103': [8, 25, 40], 'Heat 104': [9, 24, 41, 56],
    'Heat 105': [4, 29, 36], 'Heat 106': [13, 20, 45, 52],
    'Heat 107': [5, 28, 37], 'Heat 108': [12, 21, 44, 53],
    'Heat 109': [2, 31, 34], 'Heat 110': [15, 18, 47, 50],
    'Heat 111': [7, 26, 39], 'Heat 112': [10, 23, 42, 55],
    'Heat 113': [3, 30, 35], 'Heat 114': [14, 19, 46, 51],
    'Heat 115': [6, 27, 38], 'Heat 116': [11, 22, 43, 54]}

#Heat Pairs - prior heats and feed into heats
bef_aft_ht_pairs = [((101, 102), (201, 202)),
                     ((103, 104), (203, 204)),
                     ((105, 106), (205, 206)),
                     ((107, 108), (207, 208)),
                     ((109, 110), (209, 210)), #210 becomes 202 for 56
                     ((111, 112), (211, 212)), #212 becomes 204 for 56
                     ((113, 114), (213, 214)), #214 becomes 206 for 56
                     ((115, 116), (215, 216)), #216 becomes 208 for 56
                     ((201, 203), (301, 302)),
                     ((205, 207), (305, 306)),
                     ((209, 211), (309, 310)),
                     ((213, 215), (313, 314)),
                     ((202, 204), (303, 304)),
                     ((206, 208), (307, 308)),
                     ((210, 212), (311, 312)), #remove this line for 56, include for 64
                     ((214, 216), (315, 316)), #remove this line for 56, include for 64
                     ((301, 305), (416, 414)),
                     ((309, 313), (415, 413)),
                     ((302, 306), (412, 410)),
                     ((310, 314), (411, 409)),
                     ((303, 307), (408, 406)),
                     ((311, 315), (407, 405)), #remove this line for 56, include for 64
                     ((304, 308), (404, 402)),
                     ((312, 316), (403, 401)), #remove this line for 56, include for 64
                     ((416, 415), (516, 515)),
                     ((414, 413), (514, 513)),
                     ((412, 411), (512, 511)),
                     ((410, 409), (510, 509)),
                     ((408, 407), (508, 507)),
                     ((406, 405), (506, 505)),
                     ((404, 403), (504, 503)),
                     ((402, 401), (502, 501))]

bef_aft_ht_pairs_fiftysix = [((101, 102), (201, 202)),
                     ((103, 104), (203, 204)),
                     ((105, 106), (205, 206)),
                     ((107, 108), (207, 208)),
                     ((109, 110), (209, 202)), #210 becomes 202 for 56
                     ((111, 112), (211, 204)), #212 becomes 204 for 56
                     ((113, 114), (213, 206)), #214 becomes 206 for 56
                     ((115, 116), (215, 208)), #216 becomes 208 for 56
                     ((201, 203), (301, 302)),
                     ((205, 207), (305, 306)),
                     ((209, 211), (309, 310)),
                     ((213, 215), (313, 314)),
                     ((202, 204), (303, 304)),
                     ((206, 208), (307, 308)),
                     #((210, 212), (311, 312)), #remove this line for 56, include for 64
                     #((214, 216), (315, 316)), #remove this line for 56, include for 64
                     ((301, 305), (416, 414)),
                     ((309, 313), (415, 413)),
                     ((302, 306), (412, 410)),
                     ((310, 314), (411, 409)),
                     ((303, 307), (408, 406)),
                     #((311, 315), (407, 405)), #remove this line for 56, include for 64
                     ((304, 308), (404, 402)),
                     #((312, 316), (403, 401)), #remove this line for 56, include for 64
                     ((416, 415), (516, 515)),
                     ((414, 413), (514, 513)),
                     ((412, 411), (512, 511)),
                     ((410, 409), (510, 509)),
                     ((408, 408), (508, 508)), #407, 507 are empty - same group of 6 for 408, 508
                     ((406, 406), (506, 506)), #405, 505 are empty - same group of 6 for 406, 506
                     ((404, 404), (504, 504)), #403, 503 are empty - same group of 6 for 404, 504
                     ((402, 402), (502, 502))] #401, 501 are empty - same group of 6 for 402, 502

#Only needed for 56 person bracket; don't need for 64 person bracket
six_person_heats_R2_R3 = [202, 204, 206, 208, 303, 304, 307, 308]
six_person_heats_R4 = [408, 406, 404, 402]

#Bracket columns:
columns = ['Round', 'Nxt_Heat', 'First_name', 'Surname', 'Time', 'Nxt_Heat_Time']

#Heat start times:
#Round 1 - 11:15am - 12pm
#Round 2 - 2:15 - 3:00pm
#Round 3 - 4:15 - 5pm
#Round 4 - 9:15 - 10am
#Round 5 - 11:15am - 12pm
start_times = {'Heat 101': '11:15am',
             'Heat 102': '11:18am',
             'Heat 103': '11:21am',
             'Heat 104': '11:24am',
             'Heat 105': '11:27am',
             'Heat 106': '11:30am',
             'Heat 107': '11:33am',
             'Heat 108': '11:36am',
             'Heat 109': '11:39am',
             'Heat 110': '11:42am',
             'Heat 111': '11:45am',
             'Heat 112': '11:48am',
             'Heat 113': '11:51am',
             'Heat 114': '11:54am',
             'Heat 115': '11:57am',
             'Heat 116': '12:00pm',
             'Heat 201': '2:15pm',
             'Heat 202': '2:18pm',
             'Heat 203': '2:21pm',
             'Heat 204': '2:24pm',
             'Heat 205': '2:27pm',
             'Heat 206': '2:30pm',
             'Heat 207': '2:33pm',
             'Heat 208': '2:36pm',
             'Heat 209': '2:39pm',
             'Heat 210': '2:42pm',
             'Heat 211': '2:45pm',
             'Heat 212': '2:48pm',
             'Heat 213': '2:51pm',
             'Heat 214': '2:54pm',
             'Heat 215': '2:57pm',
             'Heat 216': '3:00pm',
             'Heat 301': '4:15pm',
             'Heat 302': '4:18pm',
             'Heat 303': '4:21pm',
             'Heat 304': '4:24pm',
             'Heat 305': '4:27pm',
             'Heat 306': '4:30pm',
             'Heat 307': '4:33pm',
             'Heat 308': '4:36pm',
             'Heat 309': '4:39pm',
             'Heat 310': '4:42pm',
             'Heat 311': '4:45pm',
             'Heat 312': '4:48pm',
             'Heat 313': '4:51pm',
             'Heat 314': '4:54pm',
             'Heat 315': '4:57pm',
             'Heat 316': '5:00pm',
             'Heat 401': '9:15am',
             'Heat 402': '9:18am',
             'Heat 403': '9:21am',
             'Heat 404': '9:24am',
             'Heat 405': '9:27am',
             'Heat 406': '9:30am',
             'Heat 407': '9:33am',
             'Heat 408': '9:36am',
             'Heat 409': '9:39am',
             'Heat 410': '9:42am',
             'Heat 411': '9:45am',
             'Heat 412': '9:48am',
             'Heat 413': '9:51am',
             'Heat 414': '9:54am',
             'Heat 415': '9:57am',
             'Heat 416': '10:00am',
             'Heat 501': '11:15am',
             'Heat 502': '11:18am',
             'Heat 503': '11:21am',
             'Heat 504': '11:24am',
             'Heat 505': '11:27am',
             'Heat 506': '11:30am',
             'Heat 507': '11:33am',
             'Heat 508': '11:36am',
             'Heat 509': '11:39am',
             'Heat 510': '11:42am',
             'Heat 511': '11:45am',
             'Heat 512': '11:48am',
             'Heat 513': '11:51am',
             'Heat 514': '11:54am',
             'Heat 515': '11:57am',
             'Heat 516': '12:00pm'}

In [3]:
sart18_56 = SART(r0_seeds_fiftysix, bef_aft_ht_pairs_fiftysix, columns, start_times, six_person_heats_R2_R3, six_person_heats_R4)

#### Call Functions to prepare the keys for our DataFrame
- Using the r0_seeds, h_pairs, and fd_into_ht_pairs data
- This is done in a few functions behind the scenes for this class

In [4]:
sart18_56.prepare_sd_h_keys(alter_for_fiftysix=True)

#### Create the Bracket DataFrame

In [5]:
sart18_56.create_bracket()

In [6]:
sart18_56.bracket_df.head()

Round  Nxt_Heat First_name Surname Time Nxt_Heat_Time
Seed                                                      
1        0  Heat 101        NaN     NaN  NaN       11:15am
2        0  Heat 109        NaN     NaN  NaN       11:39am
3        0  Heat 113        NaN     NaN  NaN       11:51am
4        0  Heat 105        NaN     NaN  NaN       11:27am
5        0  Heat 107        NaN     NaN  NaN       11:33am

In [7]:
sart18_56.bracket_df.info()
#for a bracket of 56 people and 5 rounds, total s/b 280 and it is

<class 'pandas.core.frame.DataFrame'>
Index: 280 entries, 1 to W416
Data columns (total 6 columns):
Round            280 non-null object
Nxt_Heat         280 non-null object
First_name       0 non-null object
Surname          0 non-null object
Time             0 non-null object
Nxt_Heat_Time    280 non-null object
dtypes: object(6)
memory usage: 15.3+ KB


In [8]:
sart18_56.bracket_df[sart18_56.bracket_df['Nxt_Heat']=='Heat 504']

Round  Nxt_Heat First_name Surname Time Nxt_Heat_Time
Seed                                                        
404-Q1     4  Heat 504        NaN     NaN  NaN       11:24am
404-Q2     4  Heat 504        NaN     NaN  NaN       11:24am
404-Q3     4  Heat 504        NaN     NaN  NaN       11:24am
404-Q4     4  Heat 504        NaN     NaN  NaN       11:24am
404-Q5     4  Heat 504        NaN     NaN  NaN       11:24am
404-Q6     4  Heat 504        NaN     NaN  NaN       11:24am

In [9]:
sart18_56.bracket_df.filter(like="204", axis=0)

Round  Nxt_Heat First_name Surname Time Nxt_Heat_Time
Seed                                                             
202/204-Q1      2  Heat 303        NaN     NaN  NaN        4:21pm
202/204-Q10     2  Heat 304        NaN     NaN  NaN        4:24pm
202/204-Q2      2  Heat 303        NaN     NaN  NaN        4:21pm
202/204-Q3      2  Heat 303        NaN     NaN  NaN        4:21pm
202/204-Q4      2  Heat 303        NaN     NaN  NaN        4:21pm
202/204-Q5      2  Heat 304        NaN     NaN  NaN        4:24pm
202/204-Q6      2  Heat 304        NaN     NaN  NaN        4:24pm
202/204-Q7      2  Heat 304        NaN     NaN  NaN        4:24pm
202/204-Q8      2  Heat 304        NaN     NaN  NaN        4:24pm
202/204-Q9      2  Heat 304        NaN     NaN  NaN        4:24pm
W204            2  Heat 303        NaN     NaN  NaN        4:21pm

## Time Trial

#### Process the time trial results
- Use the CSV results file pulled from SportSoftware
- Address any ties, mp's, dnf's, and dns's as shown below

In [10]:
sart18_56.process_time_trial_results('2018_TestFiles_from2017/TT_R0_Results.csv')

In [11]:
sart18_56._check_TT_for_ties()

'Warning: Ties exist - diff in list length is 9.  Fix before proceeding.'

In [12]:
sart18_56.tt_df_cleaned.tail(10)

Surname First_name     Time  Seed
64    Kelley        Jud  0:13:06    65
65  Forgrave        Bob  0:13:08    66
66     Ricks     Kristy  0:13:21    67
67     Byers       Kate  0:13:45    68
68    Nasman     Linnea  0:13:45    69
69  Buchholz     Larson  0:14:23    70
70    Klinge       Jill  0:14:45    71
71       Lee    Brandon  0:17:06    72
72   Hopkins       Kyle  0:17:48    73
73   Hopkins      Jared  0:33:52    74

In [13]:
sart18_56.tt_df_cleaned.sort_values(by='Seed', inplace=True)

#Adjusting seeds to break ties based on time at go control:

#Chris, Brett
sart18_56.tt_df_cleaned.loc['21', ['Time']] = '0:09:24'
sart18_56.tt_df_cleaned.loc['22', ['Time']] = '0:09:24.5'

#Ethan, Carlo
sart18_56.tt_df_cleaned.loc['24', ['Seed']] = 26
sart18_56.tt_df_cleaned.loc['24', ['Time']] = '0:09:26.5'
sart18_56.tt_df_cleaned.loc['25', ['Seed']] = 25
sart18_56.tt_df_cleaned.loc['25', ['Time']] = '0:09:26'

#Ott, Kyle
sart18_56.tt_df_cleaned.loc['27', ['Time']] = '0:09:35'
sart18_56.tt_df_cleaned.loc['28', ['Time']] = '0:09:35.5'

#Rachel, Matt F
sart18_56.tt_df_cleaned.loc['31', ['Time']] = '0:09:51'
sart18_56.tt_df_cleaned.loc['32', ['Time']] = '0:09:51.5'

#David V, RJ
sart18_56.tt_df_cleaned.loc['39', ['Seed']] = 41
sart18_56.tt_df_cleaned.loc['39', ['Time']] = '0:10:13.5'
sart18_56.tt_df_cleaned.loc['40', ['Seed']] = 40
sart18_56.tt_df_cleaned.loc['40', ['Time']] = '0:10:13'

#Christophe, Ryan B
sart18_56.tt_df_cleaned.loc['43', ['Seed']] = 45
sart18_56.tt_df_cleaned.loc['43', ['Time']] = '0:10:17.5'
sart18_56.tt_df_cleaned.loc['44', ['Seed']] = 44
sart18_56.tt_df_cleaned.loc['44', ['Time']] = '0:10:17'

#Sherri Jessica, Joanne
sart18_56.tt_df_cleaned.loc['48', ['Seed']] = 49
sart18_56.tt_df_cleaned.loc['48', ['Time']] = '0:10:36'
sart18_56.tt_df_cleaned.loc['49', ['Seed']] = 51
sart18_56.tt_df_cleaned.loc['49', ['Time']] = '0:10:36.5'
sart18_56.tt_df_cleaned.loc['50', ['Seed']] = 50
sart18_56.tt_df_cleaned.loc['50', ['Time']] = '0:10:36.2'

#Kate, Linnea
sart18_56.tt_df_cleaned.loc['67', ['Time']] = '0:13:45'
sart18_56.tt_df_cleaned.loc['68', ['Time']] = '0:13:45.5'

#These steps completed by reviewing data and pulling tie-breakers from SS; tie break is who is ahead at the go control

NOT NEEDED FOR TEST - ONLY DOING 56 PEOPLE

#Add DNS's
sart17.tt_df_cleaned.loc['74', ['Surname']] = 'Cassata'
sart17.tt_df_cleaned.loc['74', ['First_name']] = 'Julie'
sart17.tt_df_cleaned.loc['74', ['Time']] = '0:59:00'
sart17.tt_df_cleaned.loc['74', ['Seed']] = 75
#sart17.tt_df_cleaned.loc['75', ['Heat']] = 116 #get from bracket_df

sart17.tt_df_cleaned.loc['75', ['Surname']] = 'Bone'
sart17.tt_df_cleaned.loc['75', ['First_name']] = 'Eric'
sart17.tt_df_cleaned.loc['75', ['Time']] = '0:59:10'
sart17.tt_df_cleaned.loc['75', ['Seed']] = 76
#sart17.tt_df_cleaned.loc['76', ['Heat']] = 108 #get from bracket_df

sart17.tt_df_cleaned.loc['76', ['Surname']] = 'Cutler'
sart17.tt_df_cleaned.loc['76', ['First_name']] = 'Courtney'
sart17.tt_df_cleaned.loc['76', ['Time']] = '0:59:20'
sart17.tt_df_cleaned.loc['76', ['Seed']] = 77
#sart17.tt_df_cleaned.loc['77', ['Heat']] = 106 #get from bracket_df

sart17.tt_df_cleaned.loc['77', ['Surname']] = 'Ratliff'
sart17.tt_df_cleaned.loc['77', ['First_name']] = 'Hayden'
sart17.tt_df_cleaned.loc['77', ['Time']] = '0:59:30'
sart17.tt_df_cleaned.loc['77', ['Seed']] = 78
#sart17.tt_df_cleaned.loc['78', ['Heat']] = 114 #get from bracket_df

sart17.tt_df_cleaned.loc['78', ['Surname']] = 'Smith'
sart17.tt_df_cleaned.loc['78', ['First_name']] = 'Ben'
sart17.tt_df_cleaned.loc['78', ['Time']] = '0:59:40'
sart17.tt_df_cleaned.loc['78', ['Seed']] = 79
#sart17.tt_df_cleaned.loc['79', ['Heat']] = 110 #get from bracket_df

sart17.tt_df_cleaned.loc['79', ['Surname']] = 'Gusiatnikov'
sart17.tt_df_cleaned.loc['79', ['First_name']] = 'Vladimir'
sart17.tt_df_cleaned.loc['79', ['Time']] = '0:59:50'
sart17.tt_df_cleaned.loc['79', ['Seed']] = 80
#sart17.tt_df_cleaned.loc['80', ['Heat']] = 102 #get from bracket_df

#### Add the time trial results to the Bracket DataFrame Using Seed as Key
- Now each person has their Round 1 Heat Assignment since those were already associated with each seed in the Bracket DF

In [14]:
sart18_56.add_time_trial_results()

No Ties, results added to bracket!


#### Print the .txt file with next heat assignments for use in handing out heat assignment info

In [15]:
from __future__ import print_function
print(*sart18_56.print_heat_assigns(1), sep='\n', file = open("2018_TestFiles_from2017/R1_heat_assigns.txt", 'w'))

#### Process the next round CSV for import to SportSoftware with correct heat assignments
- This function pulls in the existing CSV, updates the heat assignments, and then in the following line exports a new CSV with those new assignments

In [16]:
r1_ss_import = sart18_56.assign_nxt_ht_to_ss_import_csv('2018_TestFiles_from2017/EntryForOE-R01-Lynndale-preevent.csv', 0)
#Round must be put in as an integer here!

In [17]:
r1_ss_import.to_csv('2018_TestFiles_from2017/SS_import_R1_with_heats.csv', index=False)

## Round 1

#### Import and process the results from Round 1

- Use the CSV results pulled from SportSoftware
- Address any ties, mp's, dnf's, and dns's as shown below

In [18]:
r1_results = sart18_56.clean_results_csv('2018_TestFiles_from2017/R1_Lynndale_Results.csv')
r1_results.sort_values(by='Heat', inplace=True)

r1_results.reset_index(inplace=True, drop=True) #not required for actual event; necessary due to way test file was edited to support test
r1_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 4 columns):
Surname       56 non-null object
First_name    56 non-null object
Time          56 non-null object
Heat          56 non-null int64
dtypes: int64(1), object(3)
memory usage: 1.8+ KB


In [19]:
r1_results.head()

Surname First_name     Time  Heat
0   Ferguson    Matthew  0:25:36   101
1      Enger       Will  0:15:56   101
2  Caulfield     Rachel  0:23:49   101
3       Long     Robert  0:22:26   102
4     Gruber      Brian  0:21:15   102

In [20]:
r1_results[r1_results['Heat']==111], r1_results[r1_results['Heat']==112]

(     Surname First_name     Time  Heat
 35  Colleran     Joshua  0:23:19   111
 36  O'Connor      Ethan  0:22:19   111
 37    Laraia     Thomas  0:18:09   111,
       Surname First_name     Time  Heat
 38   Collings      Laura  0:25:00   112
 39    Doubson      Julia  0:18:09   112
 40  Potrebich       Nina  0:20:28   112
 41   Buchholz      Brett  0:21:26   112)

In [21]:
#break ties:

#Thomas L, Julia D
r1_results.loc[39, ['Time']] = '0:18:09.5'

#Set high times to drive mp and dnfs to last seeds:

#Lillian Bakker mp
#r1_results.loc['42', ['Time']] = '59:00'

#Jared Hopkins dnf
#r1_results.loc['56', ['Time']] = '59:01'

In [22]:
r1_results[r1_results['Time']=='0:18:09']

Surname First_name     Time  Heat
37  Laraia     Thomas  0:18:09   111

DONT NEED TO DO FOR TEST:
    
#Added dns'
r1_results.loc['76', ['Surname']] = 'Gusiatnikov'
r1_results.loc['76', ['First_name']] = 'Vladimir'
r1_results.loc['76', ['Time']] = '59:10'
r1_results.loc['76', ['Heat']] = 102 #get heat from bracket_df

r1_results.loc['77', ['Surname']] = 'Cutler'
r1_results.loc['77', ['First_name']] = 'Courtney'
r1_results.loc['77', ['Time']] = '59:20'
r1_results.loc['77', ['Heat']] = 114 #get heat from bracket_df

r1_results.loc['78', ['Surname']] = 'Smith'
r1_results.loc['78', ['First_name']] = 'Ben'
r1_results.loc['78', ['Time']] = '59:30'
r1_results.loc['78', ['Heat']] = 110 #get heat from bracket_df

r1_results.loc['79', ['Surname']] = 'Ratliff'
r1_results.loc['79', ['First_name']] = 'Hayden'
r1_results.loc['79', ['Time']] = '59:40'
r1_results.loc['79', ['Heat']] = 106 #get heat from bracket_df

#### Assign next round heats
- This populates the results from Round 1 in the Bracket DF as appropriate based on processing method for this bracket / tournament
- Results in each person being assigned to their appropriate next heat

In [23]:
sart18_56.nxt_ht_assigns_fiftysix(r1_results, 1)

Processing Heat Pair 101, 102 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 103, 104 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 105, 106 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 107, 108 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 109, 110 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 111, 112 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 113, 114 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 115, 116 per Normal Function
No Ties, proceeding with next heat assignments!


In [24]:
#visual for example purposes:
sart18_56.bracket_df[sart18_56.bracket_df['Nxt_Heat'] == 'Heat 208']

Round  Nxt_Heat First_name     Surname     Time Nxt_Heat_Time
Seed                                                                    
107/108-Q3     1  Heat 208       Kate       Knapp  0:20:14        2:36pm
107/108-Q4     1  Heat 208       Abra      McNair  0:21:52        2:36pm
107/108-Q5     1  Heat 208        Don  Haliburton  0:30:29        2:36pm
115/116-Q3     1  Heat 208   Benjamin       Brady  0:21:09        2:36pm
115/116-Q4     1  Heat 208       Stan       Woods  0:23:28        2:36pm
115/116-Q5     1  Heat 208       Reid      Howard  0:27:03        2:36pm

#### Print the .txt file with next heat assignments for use in handing out heat assignment info

In [25]:
print(*sart18_56.print_heat_assigns(2), sep='\n', file = open("2018_TestFiles_from2017/R2_heat_assigns.txt", 'w'))

#### Process the next round CSV for import to SportSoftware with correct heat assignments
- This function pulls in the existing CSV, updates the heat assignments, and then in the following line exports a new CSV with those new assignments

In [26]:
r2_ss_import = sart18_56.assign_nxt_ht_to_ss_import_csv('2018_TestFiles_from2017/EntryForOE-R02-EdmondsCC-preevent.csv', 1)
#Round must be put in as an integer here!

In [27]:
r2_ss_import.to_csv('2018_TestFiles_from2017/SS_import_R2_with_heats.csv', index=False)

In [28]:
r2_ss_import[r2_ss_import['Long']=='Heat 208']

OE0001  Stno  XStno   Chipno  Database Id     Surname First name  YB  S  \
19     NaN  1028    NaN  1402418           28  Haliburton        Don NaN  M   
21     NaN  1032    NaN  2053404           32      Howard       Reid NaN  M   
24     NaN  1037    NaN  7204466           37       Knapp       Kate NaN  F   
28     NaN  1041    NaN  8638301           41      McNair       Abra NaN  F   
41     NaN  1060    NaN  2076094           60       Woods       Stan NaN  M   
44     NaN  1064    NaN  2068620           64       Brady   Benjamin NaN  M   

    Block       ...         EMail  Rented  Start fee  Paid  Team  Course no.  \
19    NaN       ...           NaN     NaN          0     X   NaN         NaN   
21    NaN       ...           NaN     NaN          0     X   NaN         NaN   
24    NaN       ...           NaN     NaN          0     X   NaN         NaN   
28    NaN       ...           NaN     NaN          0     X   NaN         NaN   
41    NaN       ...           NaN     NaN          0     X   NaN         NaN   
44    NaN       ...           NaN     NaN          0     X   NaN         NaN   

    Course  km   m  Course controls  
19     NaN NaN NaN              NaN  
21     NaN NaN NaN              NaN  
24     NaN NaN NaN              NaN  
28     NaN NaN NaN              NaN  
41     NaN NaN NaN              NaN  
44     NaN NaN NaN              NaN  

[6 rows x 57 columns]

## Round 2

#### Import and process the results from Round 2

- Use the CSV results pulled from SportSoftware
- Address any ties, mp's, dnf's, and dns's as shown below

In [29]:
r2_results = sart18_56.clean_results_csv('2018_TestFiles_from2017/R2_EdmondsCC_Results.csv')
r2_results.sort_values(by='Heat', inplace=True)

r2_results.reset_index(inplace=True, drop=True) #not required for actual event; necessary due to way test file was edited to support test

r2_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 4 columns):
Surname       56 non-null object
First_name    56 non-null object
Time          56 non-null object
Heat          56 non-null int64
dtypes: int64(1), object(3)
memory usage: 1.8+ KB


In [30]:
r2_results[r2_results['Heat']==204]

Surname First_name     Time  Heat
14    Colleran     Joshua  0:19:18   204
15      Jensen    Rebecca  0:19:23   204
16    Collings      Laura  0:19:24   204
17       Tarry    Stephen  0:22:41   204
18    O'Connor      Ethan  0:17:53   204
19  Giacometti      Carlo  0:17:25   204

In [31]:
#break ties:

#Format: r1_results.loc['67', ['Time']] = '17:19.5'

#Set high times to drive mp and dnfs to last seeds:

#Tom Herrnstein, mp
r2_results.loc[45, ['Time']] = '55:10'

#Bruce C, mp
r2_results.loc[46, ['Time']] = '55:20'

#Don H, dsq olive green
r2_results.loc[26, ['Time']] = '55:30'

DONT NEED FOR TEST

#Added dns's
r2_results.loc['76', ['Surname']] = 'Gusiatnikov'
r2_results.loc['76', ['First_name']] = 'Vladimir'
r2_results.loc['76', ['Time']] = '59:10'
r2_results.loc['76', ['Heat']] = 202 #get heat from bracket_df

r2_results.loc['77', ['Surname']] = 'Hopkins'
r2_results.loc['77', ['First_name']] = 'Kyle'
r2_results.loc['77', ['Time']] = '59:20'
r2_results.loc['77', ['Heat']] = 204 #get heat from bracket_df

r2_results.loc['78', ['Surname']] = 'Smith'
r2_results.loc['78', ['First_name']] = 'Ben'
r2_results.loc['78', ['Time']] = '59:30'
r2_results.loc['78', ['Heat']] = 210 #get heat from bracket_df

r2_results.loc['79', ['Surname']] = 'Ratliff'
r2_results.loc['79', ['First_name']] = 'Hayden'
r2_results.loc['79', ['Time']] = '59:40'
r2_results.loc['79', ['Heat']] = 206 #get heat from bracket_df

#### Assign next round heats
- This populates the results from Round 1 in the Bracket DF as appropriate based on processing method for this bracket / tournament
- Results in each person being assigned to their appropriate next heat

In [32]:
sart18_56.nxt_ht_assigns_fiftysix(r2_results, 2)

Processing Heat Pair 201, 203 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 205, 207 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 209, 211 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 213, 215 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 202, 204 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 206, 208 per Normal Function
No Ties, proceeding with next heat assignments!


In [33]:
#visual for example purposes:
sart18_56.bracket_df[sart18_56.bracket_df['Nxt_Heat'] == 'Heat 303']

Round  Nxt_Heat  First_name     Surname     Time Nxt_Heat_Time
Seed                                                                     
202/204-Q1     2  Heat 303       Ethan    O'Connor  0:17:53        4:21pm
202/204-Q2     2  Heat 303      Joanne       Woods  0:18:50        4:21pm
202/204-Q3     2  Heat 303      Joshua    Colleran  0:19:18        4:21pm
202/204-Q4     2  Heat 303     Rebecca      Jensen  0:19:23        4:21pm
W202           2  Heat 303  Anastasiya    Gordeeva  0:16:07        4:21pm
W204           2  Heat 303       Carlo  Giacometti  0:17:25        4:21pm

#### Print the .txt file with next heat assignments for use in handing out heat assignment info

In [34]:
print(*sart18_56.print_heat_assigns(3), sep='\n', file = open("2018_TestFiles_from2017/R3_heat_assigns.txt", 'w'))

#### Process the next round CSV for import to SportSoftware with correct heat assignments
- This function pulls in the existing CSV, updates the heat assignments, and then in the following line exports a new CSV with those new assignments

In [35]:
r3_ss_import = sart18_56.assign_nxt_ht_to_ss_import_csv('2018_TestFiles_from2017/EntryForOE-R03-LynnwoodGolf-preevent.csv', 2)
#Round must be put in as an integer here!

In [36]:
r3_ss_import.to_csv('2018_TestFiles_from2017/SS_import_R3_with_heats.csv', index=False)

In [37]:
r3_ss_import[r3_ss_import['Long']=='Heat 310']

OE0001  Stno  XStno   Chipno  Database Id   Surname First name  YB  S  \
3      NaN  1005    NaN   887141            5  Breseman       Rick NaN  M   
5      NaN  1007    NaN  1406561            7  Buchholz      Brett NaN  M   
11     NaN  1018    NaN  1397509           18    Devine    Cameron NaN  M   
48     NaN  1070    NaN  2033399           70   Doubson      Julia NaN  F   

    Block       ...         EMail  Rented  Start fee  Paid  Team  Course no.  \
3     NaN       ...           NaN     NaN          0     X   NaN         NaN   
5     NaN       ...           NaN     NaN          0     X   NaN         NaN   
11    NaN       ...           NaN     NaN          0     X   NaN         NaN   
48    NaN       ...           NaN     NaN          0     X   NaN         NaN   

    Course  km   m  Course controls  
3      NaN NaN NaN              NaN  
5      NaN NaN NaN              NaN  
11     NaN NaN NaN              NaN  
48     NaN NaN NaN              NaN  

[4 rows x 57 columns]

## Round 3

#### Import and process the results from Round 3

- Use the CSV results pulled from SportSoftware
- Address any ties, mp's, dnf's, and dns's as shown below

In [38]:
r3_results = sart18_56.clean_results_csv('2018_TestFiles_from2017/R3_LynnwoodGolf_Results.csv')
r3_results.sort_values(by='Heat', inplace=True)

r3_results.info()


<class 'pandas.core.frame.DataFrame'>
Index: 54 entries, 53 to 19
Data columns (total 4 columns):
Surname       54 non-null object
First_name    54 non-null object
Time          54 non-null object
Heat          54 non-null int64
dtypes: int64(1), object(3)
memory usage: 2.1+ KB


In [39]:
r3_results.reset_index(inplace=True, drop=True)

In [40]:
r3_results.tail()

Surname First_name     Time  Heat
49  Christopherson      Bruce  0:20:23   313
50       Grandjean      Susan  0:21:13   314
51        Sherwood       Emma  0:19:11   314
52           Golde      Peter  0:26:19   314
53          Lawson      Chris  0:22:47   314

In [41]:
#break ties:
#no ties to break

#Set high times to drive mp and dnfs to last seeds:

#Don Haliburton, mp
r3_results.loc[33, ['Time']] = '55:10'


#Add dns's:

#r3_results.loc['76', ['Surname']] = 'Gusiatnikov'
#r3_results.loc['76', ['First_name']] = 'Vladimir'
#r3_results.loc['76', ['Time']] = '59:10'
#r3_results.loc['76', ['Heat']] = 304 #get heat from bracket_df

r3_results.loc[54, ['Surname']] = 'Prior'
r3_results.loc[54, ['First_name']] = 'Mark'
r3_results.loc[54, ['Time']] = '59:20'
r3_results.loc[54, ['Heat']] = 301 #get heat from bracket_df

r3_results.loc[55, ['Surname']] = 'Devine'
r3_results.loc[55, ['First_name']] = 'Cameron'
r3_results.loc[55, ['Time']] = '59:30'
r3_results.loc[55, ['Heat']] = 310 #get heat from bracket_df

#r3_results.loc['79', ['Surname']] = 'Ratliff'
#r3_results.loc['79', ['First_name']] = 'Hayden'
#r3_results.loc['79', ['Time']] = '59:40'
#r3_results.loc['79', ['Heat']] = 303 #get heat from bracket_df

#### Assign next round heats
- This populates the results from Round 1 in the Bracket DF as appropriate based on processing method for this bracket / tournament
- Results in each person being assigned to their appropriate next heat

In [42]:
sart18_56.nxt_ht_assigns_fiftysix(r3_results, 3)


Processing Heat Pair 301, 305 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 309, 313 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 302, 306 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 310, 314 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 303, 307 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 304, 308 per Normal Function
No Ties, proceeding with next heat assignments!


In [43]:
#visual for example purposes:
sart18_56.bracket_df[(sart18_56.bracket_df['Nxt_Heat'] == 'Heat 404')]


Round  Nxt_Heat First_name     Surname     Time Nxt_Heat_Time
Seed                                                                    
304/308-Q1     3  Heat 404       Kate       Knapp  0:19:59        9:24am
304/308-Q2     3  Heat 404      Emily        Ross  0:20:10        9:24am
304/308-Q3     3  Heat 404        Tim  Waterhouse  0:22:31        9:24am
304/308-Q4     3  Heat 404    Matthew    Ferguson  0:23:21        9:24am
W304           3  Heat 404     Rachel   Caulfield  0:22:05        9:24am
W308           3  Heat 404   Benjamin       Brady  0:19:37        9:24am

#### Print the .txt file with next heat assignments for use in handing out heat assignment info

In [44]:
print(*sart18_56.print_heat_assigns(4), sep='\n', file = open("2018_TestFiles_from2017/R4_heat_assigns.txt", 'w'))

#### Process the next round CSV for import to SportSoftware with correct heat assignments
- This function pulls in the existing CSV, updates the heat assignments, and then in the following line exports a new CSV with those new assignments

In [45]:
r4_ss_import = sart18_56.assign_nxt_ht_to_ss_import_csv('2018_TestFiles_from2017/EntryForOE-R04-SouthSeattleColl1-preevent.csv', 3)
#Round must be put in as an integer here!

In [46]:
r4_ss_import.to_csv('2018_TestFiles_from2017/SS_import_R4_with_heats.csv', index=False)


In [68]:
r4_ss_import[r4_ss_import['Long']=='Heat 406']

OE0001  Stno  XStno   Chipno  Database Id       Surname First name  YB  S  \
18     NaN  1027    NaN  9102219           27  Haddad-Fonda       Kyle NaN  M   
19     NaN  1028    NaN  1402418           28    Haliburton        Don NaN  M   
20     NaN  1030    NaN  2038100           30    Herrnstein        Tom NaN  M   
22     NaN  1033    NaN  2026210           33        Jensen    Rebecca NaN  F   
42     NaN  1061    NaN  1391714           61         Woods     Joanne NaN  F   
47     NaN  1068    NaN  2092247           68      Colleran     Joshua NaN  M   

    Block       ...         EMail  Rented  Start fee  Paid  Team  Course no.  \
18    NaN       ...           NaN     NaN          0     X   NaN         NaN   
19    NaN       ...           NaN     NaN          0     X   NaN         NaN   
20    NaN       ...           NaN     NaN          0     X   NaN         NaN   
22    NaN       ...           NaN     NaN          0     X   NaN         NaN   
42    NaN       ...           NaN     NaN          0     X   NaN         NaN   
47    NaN       ...           NaN     NaN          0     X   NaN         NaN   

    Course  km   m  Course controls  
18     NaN NaN NaN              NaN  
19     NaN NaN NaN              NaN  
20     NaN NaN NaN              NaN  
22     NaN NaN NaN              NaN  
42     NaN NaN NaN              NaN  
47     NaN NaN NaN              NaN  

[6 rows x 57 columns]

# Round 4

#### Import and process the results from Round 4

- Use the CSV results pulled from SportSoftware
- Address any ties, mp's, dnf's, and dns's as shown below

In [48]:
r4_results = sart18_56.clean_results_csv('2018_TestFiles_from2017/R4_SSC1_Results.csv')
r4_results.sort_values(by='Heat', inplace=True)

r4_results.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55 entries, 4 to 51
Data columns (total 4 columns):
Surname       55 non-null object
First_name    55 non-null object
Time          54 non-null object
Heat          55 non-null int64
dtypes: int64(1), object(3)
memory usage: 2.1+ KB


In [49]:
r4_results.reset_index(inplace=True, drop=True)

In [66]:
r4_results[r4_results['Heat']==404]

Surname First_name     Time   Heat
6    Caulfield     Rachel  0:22:59  404.0
7        Brady   Benjamin  0:16:51  404.0
8         Ross      Emily  0:19:01  404.0
9        Knapp       Kate  0:19:25  404.0
10  Waterhouse        Tim  0:19:40  404.0

In [67]:
r4_results.tail()

Surname First_name       Time   Heat
51     Jones       Eric    0:14:13  416.0
52    Bakker      David    0:13:41  416.0
53    Rennie     Graeme  0:13:38.5  416.0
54     Enger       Will    0:13:27  416.0
55  Ferguson    Matthew      59:30  406.0

In [169]:
#break ties:

r4_results.loc[47, ['Time']] = '0:13:38'
r4_results.loc[53, ['Time']] = '0:13:38.5'


#Set high times to drive mp and dnfs to last seeds:

#r4_results.loc['4', ['Time']] = '55:40' #Lillian B dnf
#r4_results.loc['3', ['Time']] = '55:35'#Bob F mp
r4_results.loc[30, ['Time']] = '00:55:30' #Kevin M dnf
#r4_results.loc['12', ['Time']] = '55:25' #Jared H mp
r4_results.loc[23, ['Time']] = '00:55:20' #Sue G mp
r4_results.loc[46, ['Time']] = '00:55:15' #Ott mp
r4_results.loc[43, ['Time']] = '00:55:10' #Tori B mp


#Added dns's

#Format:
#r4_results.loc['77', ['Surname']] = 'Gusiatnikov'
#r4_results.loc['77', ['First_name']] = 'Vladimir'
#r4_results.loc['77', ['Time']] = '59:10'
#r4_results.loc['77', ['Heat']] = 402 #get heat from bracket_df

#r4_results.loc['78', ['Surname']] = 'Ratliff'
#r4_results.loc['78', ['First_name']] = 'Hayden'
#r4_results.loc['78', ['Time']] = '59:20'
#r4_results.loc['78', ['Heat']] = 402 #get heat from bracket_df

r4_results.loc[55, ['Surname']] = 'Ferguson'
r4_results.loc[55, ['First_name']] = 'Matthew'
r4_results.loc[55, ['Time']] = '00:59:30'
r4_results.loc[55, ['Heat']] = 404 #get heat from bracket_df

#### Assign next round heats
- This populates the results from Round 1 in the Bracket DF as appropriate based on processing method for this bracket / tournament
- Results in each person being assigned to their appropriate next heat

In [170]:
sart18_56.nxt_ht_assigns_fiftysix(r4_results, 4)

Processing Heat Pair 416, 415 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 414, 413 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 412, 411 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 410, 409 per Normal Function
No Ties, proceeding with next heat assignments!
Processing Heat Pair 408, 408 for R4 to R5 Unique Heats
Processing Heat Pair 406, 406 for R4 to R5 Unique Heats
Processing Heat Pair 404, 404 for R4 to R5 Unique Heats
Processing Heat Pair 402, 402 for R4 to R5 Unique Heats


In [171]:
#visual for example purposes:
sart18_56.bracket_df[(sart18_56.bracket_df['Nxt_Heat'] == 'Heat 504')]

Round  Nxt_Heat First_name     Surname      Time Nxt_Heat_Time
Seed                                                                 
404-Q1     4  Heat 504    Matthew    Ferguson  00:59:30       11:24am
404-Q2     4  Heat 504   Benjamin       Brady   0:16:51       11:24am
404-Q3     4  Heat 504      Emily        Ross   0:19:01       11:24am
404-Q4     4  Heat 504       Kate       Knapp   0:19:25       11:24am
404-Q5     4  Heat 504        Tim  Waterhouse   0:19:40       11:24am
404-Q6     4  Heat 504     Rachel   Caulfield   0:22:59       11:24am

#### Print the .txt file with next heat assignments for use in handing out heat assignment info

In [172]:
print(*sart18_56.print_heat_assigns(5), sep='\n', file = open("2018_TestFiles_from2017/R5_heat_assigns.txt", 'w'))

#### Process the next round CSV for import to SportSoftware with correct heat assignments
- This function pulls in the existing CSV, updates the heat assignments, and then in the following line exports a new CSV with those new assignments

In [173]:
r5_ss_import = sart18_56.assign_nxt_ht_to_ss_import_csv('2018_TestFiles_from2017/EntryForOE-R05-SouthSeattleColl2-Champs-preevent.csv', 4)
#Round must be put in as an integer here!

In [174]:
r5_ss_import.to_csv('2018_TestFiles_from2017/SS_import_R5_with_heats.csv')

In [175]:
r5_ss_import[r5_ss_import['Long']=='Heat 504']

OE0001  Stno  XStno   Chipno  Database Id     Surname First name  YB  S  \
6      NaN  1010    NaN  1402428           10   Caulfield     Rachel NaN  F   
24     NaN  1037    NaN  7204466           37       Knapp       Kate NaN  F   
34     NaN  1050    NaN   888574           50        Ross      Emily NaN  F   
39     NaN  1058    NaN  2053405           58  Waterhouse        Tim NaN  M   
44     NaN  1064    NaN  2068620           64       Brady   Benjamin NaN  M   
49     NaN  1071    NaN  2025780           71    Ferguson    Matthew NaN  M   

    Block       ...         EMail  Rented  Start fee  Paid  Team  Course no.  \
6     NaN       ...           NaN     NaN          0     X   NaN         NaN   
24    NaN       ...           NaN     NaN          0     X   NaN         NaN   
34    NaN       ...           NaN     NaN          0     X   NaN         NaN   
39    NaN       ...           NaN     1.0          0     X   NaN         NaN   
44    NaN       ...           NaN     NaN          0     X   NaN         NaN   
49    NaN       ...           NaN     NaN          0     X   NaN         NaN   

    Course  km   m  Course controls  
6      NaN NaN NaN              NaN  
24     NaN NaN NaN              NaN  
34     NaN NaN NaN              NaN  
39     NaN NaN NaN              NaN  
44     NaN NaN NaN              NaN  
49     NaN NaN NaN              NaN  

[6 rows x 57 columns]

## Round 5

#### Import and process the results from Round 5

- Use the CSV results pulled from SportSoftware
- Address any ties, mp's, dnf's, and dns's as shown below

In [184]:
r5_results = sart18_56.clean_results_csv('2018_TestFiles_from2017/R5_SSC2Champs_Results.csv')

In [185]:
r5_results.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55 entries, 51 to 0
Data columns (total 4 columns):
Surname       55 non-null object
First_name    55 non-null object
Time          55 non-null object
Heat          55 non-null int64
dtypes: int64(1), object(3)
memory usage: 2.1+ KB


In [186]:
#break ties:
#Format: r5_results.loc['11', ['Time']] = '29:45.5' #Jud vs Terry

#Set high times to drive mp and dnfs (and disqs) to last seeds:

#r5_results.loc['4', ['Time']] = '55:00' #Courtney C mp
#r5_results.loc['17', ['Time']] = '55:10' #Shannon C mp
r5_results.loc[50, ['Time']] = '00:55:20' #Janne M mp
r5_results.loc[24, ['Time']] = '00:55:30' #Christophe mp

#Added dns's

#r5_results.loc['75', ['Surname']] = 'Lee'
#r5_results.loc['75', ['First_name']] = 'Brandon'
#r5_results.loc['75', ['Time']] = '59:10'
#r5_results.loc['75', ['Heat']] = 501 #get heat from bracket_df

#r5_results.loc['76', ['Surname']] = 'Bakker'
#r5_results.loc['76', ['First_name']] = 'Lillian'
#r5_results.loc['76', ['Time']] = '59:20'
#r5_results.loc['76', ['Heat']] = 501 #get heat from bracket_df

#r5_results.loc['77', ['Surname']] = 'Gusiatnikov'
#r5_results.loc['77', ['First_name']] = 'Vladimir'
#r5_results.loc['77', ['Time']] = '59:30'
#r5_results.loc['77', ['Heat']] = 501 #get heat from bracket_df

#r5_results.loc['78', ['Surname']] = 'Ratliff'
#r5_results.loc['78', ['First_name']] = 'Hayden'
#r5_results.loc['78', ['Time']] = '59:40'
#r5_results.loc['78', ['Heat']] = 501 #get heat from bracket_df

r5_results.loc[56, ['Surname']] = 'Ferguson'
r5_results.loc[56, ['First_name']] = 'Matthew'
r5_results.loc[56, ['Time']] = '00:59:50'
r5_results.loc[56, ['Heat']] = 504 #get heat from bracket_df

In [189]:
r5_results[r5_results['First_name']=='Matthew']

Surname First_name      Time   Heat
45  Ferguson    Matthew  00:59:50  504.0

#### print .txt file with final results!

In [197]:
print(*sart18_56.print_final_results(r4_results, r5_results), sep='\n', file = open("2018_TestFiles_from2017/Final_Results.txt", 'w'))

No ties, proceeding with print out
